import Head from 'next/head'
import { Home } from '../src/Home'

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Home - Ronald Prato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  )
}
